# Generated by Django 2.2.9 on 2022-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Поле изображения', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
